#+title:
Roadmap

* Ruinia Roadmap

** [[Введение]]

** Введение

Ruinia - многопользовательская текстовая ролевая игра. Вас ждет огромный мир, полный приключений, путешествий и битв.

** Ruinia: Что нас ждет
*** - Что такое Ruinia?
Ruinia - текстовая игра. Готовьтесь много писать и часто печатать.
В данной игре можно прожить сотни жизней и пройти множество путей: добра и зла, жестокого наемника и святого торговца, мудрого ученого и безумного фокусника.
Главным преимуществом Ruinia является СВОБОДА. Ваш персонаж может стать тем, кем вы захотите

*** - Чем можно будет заняться в игре?
+ Общаться и дружить с другими игроками. Сражаться плечом к плечу с боевыми товарищами. Вступить в гильдию и выполнять интересные квесты. Женитесь и выходите замуж:)
+ Путешествуйте по огромному миру, исследуя сотни интереснейших мест: города, леса, пустыни, древние развалины. Вы можете попасть даже в симуляцию-ловушку (привет, матрица)
+ Сражайся с тысячами разных противников. Накапливай опыт и осваивай новые умения.
+ Разгадывай тайны мира и выполняй сотни заданий.
+ Создавайте ценные предметы и торгуйте ими.
+ Стройте, либо покупайте различные сооружения
+ Откройте самую лучшую таверну в городе, а затем продайте ее новичку.
+ Станьте гидом для новичков и водите экскурсии по древним развалинам.
+ И еще многое другое...
