* Глев
Глев - это северный город Аусуша.
Глев окружен стеной. Около стены расположились конюшни и постоялые дворы. Первое, что замечают приезжие - это водные каналы с живой рыбой, которые вплелись в каждую улицу этого города. Второе, что замечают приезжие - высокие готические дома.

К северу от Глева находится черный океан. В югу от Глева расположено два озера, вода из которых поступает в каналы города. Два озера к югу от Глева снабжают весь город свежей рыбой, от чего в городе и пахнет рыбой.

Несмотря на то, что Глев окружен густыми лесами, город отстроен из камня, так как повышенная влажность плохо влияет на деревянные сооружения.

Внутри города расположено несколько смотрительных вышек.

Глев - очень шумный город, отовсюду можно услышать громыхающие тележки, крики продавцов, лай собак.

Центр Глева - торговая площадь, на которой находится главная достопремичательность - мраморная статуя первого главы города (его имя неизвестно, но, как передавалось из уст в уста, он крошил боевые машины голыми руками).

Еще от других городов Глев отличает то, что под ним находится подземный ярус города (для людей не столь состоятельных).

Жители Глева очень трепетно относятся к воде, рыбам и состоянию каналов. Когда-то давно озера к югу от Глева были очищены от вируса первым главой города. В те же времена, в нем завелась рыба.

Глев состоит из широких и прямых улиц, зажатых по бокам высокими зданиями со множеством балконов и "висячими" мостами, высоко соединящими одни здания с другими над наполенными тележками улицами.

Здания сделаны из самого обычного камня, так как весь камень импортируется из других городов и закупать более изысканные материалы было бы расточительным.

Здания возвышаются на пять-шесть этажей и соединены подземными проходами под основными улицами. Мало кто может позволить себе жить в целом здании; большинство живет под землей. Самые высокие здания это те, что окружают центральную площадь. В них проживают высокопоставленные лица города, а также приезжие главы других городов.

В центре города под землей находится очистное сооружение, оставленное первым главой в подарок городу, перед своим исчезновением. Несколько людей было обучено работать с ним, с тех пор знания об очистном сооружении передаются только самым талантливым ремесленникам. Работа по обеспечению очистного сооружения является очень престижной.

Большинство комнат несмотря на повышенную влажность обставлены добротной деревянной мебелью.

Большая часть торговли сосредоточена на центральной площади и в торговом районе, который находится в северной части города.

На западе города находится район развлечений, где располагаются многочисленные таверны и другие увеселительные заведения.

На востоке находится район ремесленников, там же располагаются школа и больница.

Глев - древний город, который не знал войны с момента своего основания. Каждому из жителей хватает на еду. Глев притягивает к себе ученых и изобретателей.
