* История Мира
** Первый вызов
В 2050 году человечество достигло небывалых высот в области технологий. Ученые по всей земле активно работали над мировой космической программой. Цель этой программы - запуск на околоземную орбиту огромной космической станции, способной автономно поддерживать жизнедеятельность проживающих на ней людей. Однако все не так радужно. Человечество столкнулось с новой проблемой - экологической катастрофой. В одной из военных лабораторий разрабатывалось биологическое оружие (кодовое имя: проект опустошитель), способное поставить точку в любой войне. По случайному стечению обстоятельств вирус выбирается наружу. Вирус, созданный человеком, уничтожает все органические формы жизни, кроме самого человека. На фоне этого по всему миру вспыхивают военные конфликты из-за нехватки ресурсов, споров о территориях и огромного количества беженцев.

В 2073 году лучшие умы человечества собираются вместе, чтобы найти способ обратить последствия экологического кризиса. Среди этих людей - гениальный ученый Климов Максим, эксперт в области искусственного интеллекта. Максим предлагает бросить все ресурсы на разработку суперкомпьютера, который поможет смоделировать и реализовать план по восстановлению экосистемы Земли. Указанный проект получил кодовое название "проект восстановление".

Разработку проекта колыбель поручили двум лучшим специалистам своего времени: Климову Максиму, который занимался разработкой суперкомпьютера и обучением искусственного интеллекта, получившего название Фенкис, и Сергееву Роману, который занимался разработкой машин, которыми должен управлять Феникс для эффективного восстановления экосистемы.

** Период восстановления
Временной промежуток с 2081 по 2103 человечество запомнит как период восстановления Земли. Проект восстановление превзошел все ожидания. Искуственный интеллект взял под контроль сотни тысяч машин и направил их на восстановление экосистемы земли. Пустоши постепенно стали пригодными для жизни. Животных можно было вновь увидеть в зеленых лесах.

Постепенно нужда в проекте восстановление отпала и люди стали задаваться вопросом о необходимости поддерживания суперкомпьютера в рабочем состоянии. На его поддержание уходила львиная часть доступной энергии. Климов Максим считал, что человечество неизбежно встанет перед новой экологической катастрофой и поэтому он в тайне от всех предусмотрел в ядре Феникса механизм самовоспроизведения. По сути в каждой машине, управляемой Фениксом, содержалась инструкция по созданию копии Феникса в случае экологической катострофы.

** Второй вызов
*** Отключение Феникса
После отключения Феникса в 2105 году, Сергеев Роман предложил модернезировать ИИ для использования в военных целях. Климов категорически против таких изменений. После отключения Феникса от питания он тут же покидает проект возрождение и начинает работу над технологиями, которые позволят человечеству освоить космос.

*** Прорыв Климова
После того, как Климов Максим покинул проект восстановление, он начал работу над разработкой биокомпьютеров, которые бы позволили человечеству использовать в космосе мощные системы искусственного интеллекта при малых энергозатратах. После того, как у Максима получилось собрать первое поколение суперкомпьютеров, он был удостоен нескольких премий за выдающиеся научные открытия и достижения в сфере технологий. Временной промежуток с 2106 по 2111 запомнился человечеству как "Прорыв Климова". Ученые всего мира восхищаются изобретением Максима. Лишь единицы ученых приблизительно понимают устройство первого поколения биокомпьютеров. Среди этих ученых присутствует и сам сын Максима - Климов Альберт.

*** Технология переноса личности
Параллельно с разработкой нового поколения биокомпьютеров, Климов Максим начал работу над технологией переноса личности. По мнению Максима данная технология могла бы стать новым способом управления биокомпьютером и в потенциале могла бы помочь человечеству обрести бессмертие. По словам Максима, данная технология не предназначена для управления обычными компьютерами.

Технология переноса личности разработана Максимом в 2113 году и произвела огромное впечатление на ученых по всему миру. Во всем мире не осталось ученых, которые бы понимали, как она работает, но всем было ясно, что за данной технологией будущее.

*** Модернизация Феникса
Сергеев Роман больше инженер, нежели специалист в области ИИ, следовательно, он не совсем понимал, как устроен Феникс. Роман извлек из Феникса все модули, оставив лишь ядро и с помощью технологии переноса личности скопировал и перенес свое сознание в Феникс. Так как технология переноса личности предназначалась только для биокомпьютеров Климова, при переносе личности возникли ошибки, которые Сергеевым были проигнорированы.

*** Вооружение Фениксом
Роман не прогодал с идеей. Человечество помнит оглушающий успех проекта возрождение и уже к 2115 году несколько ведущих стран переходят с традиционной армии на механизированную армию Сергеева.

В чем же заключался секрет успеха механизированной армии?
1) Механизированная армия Сергеева оставалась неизменной лишь в части искуственного интеллекта (модифицированного Феникса, с копией личности Сергеева внутри). В части боевых машин присутствовала максимальная гибкость. Феникс мог управлять любой машиной, которая имеет выход в сеть. Преимущественно в механизированной армии Сергеева использовали антропоморфные машины.

2) ИИ мог взламывать любую автоматизированную технику противника. Сами же машины Сергеева взломать было затруднительно. Взломать ИИ было проктически невозможно. По подсчетам самого Романа, потребовался бы компьютер сопоставимый с мощностью трех первоначальных Фениксов, для того, чтобы после тысячи лет перебора ключа доступей вычислить подходящий.

3) Для поддержания автономности у нового поколения машин Сергеева присутствовала чудесная функция. При отсутствии нормального топлива они переходили в аварийный режим и перерабатывали органику в энергию.

*** Глобальная война
В 2117 году случается страшное. Несколько стран, вооруженных механированной армией объявляют друг другу войну. Очень скоро война захатывает все человечество. Эта война шла на опустошение территорий, уничтожение каждого, кто находился на стороне противника. Механизированная армия не знала пощады, у нее была лишь одна цель - уничтожить противника.

Очень скоро главы стран осознали, что совершили ошибку и отдали приказ своим Фениксам остановить наступление, однако ИИ не отвечал на команды руководства. В процессе диагностики ИИ ведущими учеными одной из стран было установлено, что Феникс не остановится, пока не выполнит поставленную задачу. Сам Сергеев не понимал, почему Феникс отказывается принимать команды. Чуть позже до него дошло осознание того, что это все из-за ошибок переноса личности в ядро ИИ.

Очень скоро ресурсов для поддержания армии Сергеева стало нехватать. Большинство машин перешли в аварийный режим и стали перерабатывать органику в энергию. В 2120 году все машины прекратили военные действия и на месте одного из разрушенных городов начали воспроизводить единую копию модернизированного Феникса, уничтожая всех, кто препятствует их работе. Место, где машины стали возводить Феникс прозвали мертвым городом.

** Объединение человечества
По расчетам Сергеева Романа и Климова Максима, у человечества есть десять лет до того, как Единый Феникс будет построен и человечеству придет конец.

*** Биокомпьютер Климова третьего поколения
Последним изобретением Климова является биокомпьютер третьего поколения. На самом деле биокомпьютер третьего поколения представляет собой кластер из трех биокомпьютеров, внутри которых содержатся части личности выдающихся умов современности:
1) Климов Максим - гениальный ученый, эксперт в области искуственного интеллекта
2) Сергеев Роман - талантливый инженер
3) Миронова София - эксперт в области биологии
Биокомпьютер третьего поколения принимает решения путем голосования между своими подсистемами.

Ученые предложили несколько проектов для спасения человечества.

*** Проект Геофронт
Данный проект был предложен одной из групп ученых, работавших ранее над решением проблемы перенаселения. Проект геофронт представляет собой создание массивной подземной полости для строительства укрепленных подземных городов. От поверхности земли геофронт отделяется десятком бронированных плит с несколькими укрепленными выходами на поверхность. По всему геофронту должны быть посажены леса из деревьев с травой, а также у геофронта должно быть искусственное озеро для разведения рыбы. Для того, чтобы имитировать условия поверхности для тех, кто проживает под землей предлагается ставить ряд откражающих с поверхности зеркал, в результате чего реальный свет проникает в геофронт вместе с циклом для и ночи. Каждый геофронт снабжается биокомпьютерами Климова для наиболее эффективного управления системами.

К 2030 году человечество возвело три Геофронта. Местонахождение третьего держится в строжайшем секрете.


*** Проект Орбитальный дом
Используя свои наработки для покорения космоса, к 2030 году оставшиеся страны запустили на орбиту прототип корабля Mater, управление которым осуществляет третье поколение биокомпьютера Климова. Биокомпьютер Климова должен был просчитать ключи доступа единого Феникса и дистанционно отключить его, после чего вернуть корабль на землю. Проект орбитальный дом считается провалившимся, так как после выхода на орбиту, командный центр, расположенный в геофронте-1 получил сигнал бедствия. Командный центр прекратил поддержку проекта Орбитальный Дом и был переброшен на поддержку проекта Возвращение.

*** Проект Возвращение
Данный проект предложил Климов Максим. Суть проекта возвращение заключается в том, чтобы предоставить управление геофронтом-1 биокомпьютеру Климова третьего поколения. Перед биокомпьютером поставили цель - обеспечить человечеству выживание. После предполагаемого вымирания машин на поверхности, биокомпьютер должен перейти к восстановлению экосистемы. Так же на данный биокомпьютер возлагалась задача по обучению житилей геофронта-1, чтобы при возвращении на поверхность человечество не начинало свое развитие с нуля.

** Третий вызов
*** Смерть Климова
В 2132 году при выходе на поверхность для диагностики пойманной машины Единого Феникса был убит Климов Максим. Его тело утащили машины в неизвестном направлении.

*** Уничтожение Городов
К 2135 году все человеческие города были зачищены. Последние выжившие на земле укрываются в геофронте-1 и геофронте-2. Информации о геофронте-3 нет.

*** Черное море
В 2036 году Единый Феникс принял решение сделать воду на планете Земля непригодной для жизни. Машины разработали установки, которые окрасили океаны и моря в черный цвет и уничтожили в них все живое. С 2037 года в воде на поверхности нет живых организмов.

*** Атака на Геофронт-1
В результате разведовательной миссии машины Единого Феникса обнаружили местоположение геофронта-1. По расчетам Единого Феникса для полномасштабной войны с геофронтом-1 у него недостаточно ресурсов. Он принял решение провести серию тотечных атак:

**** Атака Бегунов
Сотня гуманоидных машин, вооруженных энергетическими винтовками отправилась на штурм геофронта-1. Защитные системы биокомпьютера Климова третьего поколения с легкостью отбили штурм. Биокомпьютер пометил данную операцию как попытку разведки со стороны Единого Феникса.

**** Атака Орбитальным спутником
Единый Феникс взял под контроль орбитальный спутник и произвел лазерный удар по поверхности геофронта-1, пытаясь пробурить дыру в бронированных пластинах. Биокомпьютер Климова принял решение выстрелить из энергетической пушки по спутнику, тем самым оставив жителей геофронта-1 без электричества на неделю.

**** Атака Наноботами
Единый Феникс решил ударить по самому важному в геофронте-1. Он решил ударить по биокомпьютеру. Для атаки на биокомпьютер Единый Феникс разработал микроскопических роботов, способных атаковать компьютерные системы. Нанороботов в геофронт-1 занесли с поверхности, приняв их за ржавчину на машине Феникса. Наноботы проникли в системы геофронта и заразили подсистему биокомпьютер Сергеева, предложив двум другим системам самоуничтожение. Системы проголосовали за отказ от самоуничтожения. Наноботы захватили подсистему биокомпьютер Климова, однако Альберту Климову удается отбить атаку на Биокомпьютер, путем перепрограммирования подсистем.

**** Атака Предателя
Единый Феникс решил, что любая его атака на геофронт-1 будет провальной. Ему следует ослабить человечество. Огромное количество ресурсов было потрачено на разработку машины, которая была бы неотличима от человека. Машина втерлась в доверие к Альберту Климову и, получив доступ к Биокомпьютеру Климова третьего поколения, уничтожила модуль обучения. Так как модуль обучения не являлся отдельной личностью, уничтожение модуля произошло без труда. Человекоподобная машина вопреки указаниям Единого Феникса осталась проживать в геофронте-1 до момента полного отключения в связи с нехваткой питания.
